INSERT = "INSERT"
DELETE = "DELETE"
COPY = "COPY"
REDO = "REDO"
UNDO = "UNDO"
DISPLAY = "DISPLAY"
PASTE = "PASTE"
EMPTY= "EMPTY"

EDITOR_FUNCTIONS = {
    INSERT: INSERT,
    DELETE: DELETE,
    COPY: COPY,
    REDO: REDO,
    UNDO: UNDO,
    DISPLAY: DISPLAY,
    PASTE: PASTE
}

UNDO_MAPPING = {
    INSERT: DELETE,
    DELETE: INSERT,
    COPY: EMPTY,
    PASTE: DELETE,
    UNDO: EMPTY,
    REDO: EMPTY,
}
