ACCEPTED = "ACCEPTED"
NEUTRAL = "NEUTRAL"
REJECTED = "REJECTED"

EVENT_STATE = {
    ACCEPTED: ACCEPTED,
    NEUTRAL: NEUTRAL,
    REJECTED: REJECTED
}

MEETING = "MEETING"
HOLIDAY = "HOLIDAY"
REMINDER = "REMINDER"
EVENT_TYPE = {
    MEETING: MEETING,
    HOLIDAY: HOLIDAY,
    REMINDER: REMINDER,

}
