EARTH_RADIUS = 6371

PENDING = "PENDING"
FREE = "FREE"
BUSY = "BUSY"
DELIVERY_EXECUTIVE_ASSIGNED = "DELIVERY_EXECUTIVE_ASSIGNED"
COMPLETED = "COMPLETED"

DELIVERY_EXECUTIVE_STATUSES = {
    FREE: FREE,
    BUSY: BUSY
}

ORDER_STATUSES = {
    PENDING: PENDING,
    DELIVERY_EXECUTIVE_ASSIGNED: DELIVERY_EXECUTIVE_ASSIGNED,
    COMPLETED: COMPLETED
}
LOW_FIRST_MILE = 10000

LOW_FIRST_MILE_STRATEGY = "LOW_FIRST_MILE_STRATEGY"
PREMIUM_FIRST_MILE_STRATEGY = "PREMIUM_FIRST_MILE_STRATEGY"

ASSIGNMENT_STRATEGIES = {
    LOW_FIRST_MILE_STRATEGY: LOW_FIRST_MILE_STRATEGY,
    PREMIUM_FIRST_MILE_STRATEGY: PREMIUM_FIRST_MILE_STRATEGY

}
