PARK = "PARK"
LEAVE = "LEAVE"

CAR_PARKING_ACTIONS = {
    PARK: PARK,
    LEAVE: LEAVE
}

EMPTY = "EMPTY"
FULL = "FULL"
NEITHER = "NEITHER"

PARKING_SLOT_STATUSES = {
    EMPTY: EMPTY,
    FULL: FULL,
    NEITHER: NEITHER
}

STATUS_ALLOCATED = "STATUS ALLOCATED"
STATUS_FREE = "STATUS FREE"

COMMAND_ACTIONS = {
    PARK: PARK,
    LEAVE: LEAVE,
    STATUS_ALLOCATED: STATUS_ALLOCATED,
    STATUS_FREE: STATUS_FREE
}